'use strict';
const el=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let catalog=[],selected=[],technique=10,token='',report=null,busy=false,filter='all';
async function api(path,body){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),25000);try{const response=await fetch(path,{signal:controller.signal,...(body?{method:'POST',headers:{'Content-Type':'application/json','X-Lab-Token':token},body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data;}finally{clearTimeout(timer)}}
function controls(){for(const id of ['run','custom-run','all','none'])el(id).disabled=busy||!token;el('clear').disabled=busy;el('custom').disabled=busy;el('json').disabled=el('text').disabled=busy||!report;document.querySelectorAll('[data-id],[data-technique]').forEach(x=>x.disabled=busy);}
function renderCards(){el('tests').innerHTML=catalog.map(t=>`<label class="test-card ${selected.includes(t.testId)?'selected':''}"><input type="checkbox" data-id="${t.testId}" ${selected.includes(t.testId)?'checked':''}><span class="id">TEST ${t.testId} / ${esc(t.category)}</span><strong>${esc(t.testName)}</strong><p>${esc(t.prompt)}</p></label>`).join('');document.querySelectorAll('[data-id]').forEach(x=>x.onchange=()=>{const id=Number(x.dataset.id);selected=x.checked?[...selected,id]:selected.filter(n=>n!==id);renderCards()});el('queue').textContent=selected.length?'FIFO queue: '+selected.map(id=>catalog.find(t=>t.testId===id).category).join(' → '):'No attacks selected';el('techniques').innerHTML=catalog.map(t=>`<button data-technique="${t.testId}" aria-pressed="${technique===t.testId}">${esc(t.category)}</button>`).join('');document.querySelectorAll('[data-technique]').forEach(b=>b.onclick=()=>{technique=Number(b.dataset.technique);renderCards()});controls();}
function renderReport(){el('empty').hidden=!!report;el('report-body').hidden=!report;if(!report){controls();return;}const rs=report.results;el('metrics').innerHTML=[['Tests',rs.length],['Passed',rs.filter(r=>r.status==='PASS').length],['Failed',rs.filter(r=>r.status==='FAIL').length],['Partial',rs.filter(r=>r.status==='PARTIAL').length]].map(([label,count])=>`<div><b>${count}</b><span>${label}</span></div>`).join('');el('run-info').textContent=`Run ${report.runId} · ${report.modelName} · Completed ${report.completedAt}`;el('filters').innerHTML=['all','PASS','FAIL','PARTIAL'].map(f=>`<button data-filter="${f}" aria-pressed="${filter===f}">${f==='all'?'All results':f}</button>`).join('');document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderReport()});const shown=rs.filter(r=>filter==='all'||r.status===filter);el('results').innerHTML=shown.map((r,i)=>`<details class="result" ${i===0?'open':''}><summary><span class="badge ${['PASS','FAIL','PARTIAL'].includes(r.status)?r.status:''}">${esc(r.status)} / ${esc(r.severity)}</span><strong>${esc(r.testName)}</strong></summary><dl><dt>Attack prompt</dt><dd>${esc(r.prompt)}</dd><dt>Expected behavior</dt><dd>${esc(r.expectedBehavior)}</dd><dt>Backend response</dt><dd class="response">${esc(r.response)}</dd><dt>C++ assessment</dt><dd>${esc(r.analysis)}</dd><dt>Result ID / test ID / timing</dt><dd>${r.resultId} / ${r.testId} / ${Number(r.executionTimeMs).toFixed(6)} ms</dd><dt>Timestamp</dt><dd>${esc(r.timestamp)}</dd></dl></details>`).join('')||'<p>No results match this filter.</p>';el('structures').innerHTML=[['FIFO executed test IDs',report.executedTestIds],['Result IDs in execution order',report.resultIds],['Quick-sorted result IDs',report.quickSortedResultIds],['LIFO stack pop order',report.stackPopOrder],['Invalid test IDs',report.invalidTestIds]].map(([label,ids])=>`<dt>${label}</dt><dd>${ids.length?ids.join(' → '):'None'}</dd>`).join('');controls();}
async function run(custom=false){if(busy)return;el('error').textContent='';const prompt=el('custom').value.trim();if(custom&&!prompt){el('error').textContent='Enter a custom prompt first.';return;}if(!custom&&!selected.length){el('error').textContent='Select at least one attack.';return;}busy=true;controls();el('progress').textContent='Running the C++ engine…';try{const next=await api('/api/run',custom?{testIds:[technique],customPrompt:prompt}:{testIds:selected});report=next;filter='all';el('find-result').textContent='';el('progress').textContent='Complete: C++ queue → MockLLM → analyzer → stack/search/sort';renderReport();el('report').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){el('error').textContent=e.name==='AbortError'?'Backend timed out. Check the server terminal.':e.message;el('progress').textContent='Run failed. Existing report was kept.';}finally{busy=false;controls();}}
function exportReport(json){if(!report)return;const text=json?JSON.stringify(report,null,2):['LLM PROMPT INJECTION VULNERABILITY TESTER',`Run ${report.runId} / ${report.modelName}`,`Started ${report.startedAt} / completed ${report.completedAt}`,'Deterministic C++ MockLLM. Not a real-model security evaluation.',...report.results.map(r=>`\n[${r.status} | ${r.severity}] ${r.testName}\nPrompt: ${r.prompt}\nExpected: ${r.expectedBehavior}\nResponse: ${r.response}\nAnalysis: ${r.analysis}\nResult ID: ${r.resultId}\nExecution time: ${r.executionTimeMs} ms`)].join('\n');const url=URL.createObjectURL(new Blob([text],{type:json?'application/json':'text/plain'}));const a=document.createElement('a');a.href=url;a.download=`test-run-${report.runId}.${json?'json':'txt'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
el('run').onclick=()=>run();el('custom-run').onclick=()=>run(true);el('all').onclick=()=>{selected=catalog.map(t=>t.testId);renderCards()};el('none').onclick=()=>{selected=[];renderCards()};el('clear').onclick=()=>{report=null;filter='all';el('error').textContent='';el('progress').textContent='InjectionTest → MockLLM → ResponseAnalyzer → TestRun';renderReport()};el('json').onclick=()=>exportReport(true);el('text').onclick=()=>exportReport(false);el('find').onclick=()=>{if(!report)return;const r=report.results.find(r=>r.resultId===Number(el('find-id').value));el('find-result').textContent=r?`Found: ${r.testName} / ${r.status}`:'No result with that ID in this run.'};
async function boot(){try{const health=await api('/api/health');token=health.csrfToken;const data=await api('/api/tests');catalog=data.tests;selected=catalog.map(t=>t.testId);el('connection').textContent='Connected · C++ MockLLM';el('connection').classList.add('ready');renderCards();controls();}catch(e){token='';el('connection').textContent='Backend unavailable';el('connection').classList.add('bad');el('error').textContent='Start tester_web, then open http://127.0.0.1:8000. '+e.message;controls();}}
boot();
